# -*- coding: utf-8 -*-
"""Plot Bee Tube

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nQixEXx8f1B8Q97JEXWnwKwhx3h_RJV
"""

!pip install jupyter-dash

!pip install plotly==5.13.0

import pandas as pd


path='/content/drive/MyDrive/Beetube/5min_clip/bee_0_head'
bee_man=pd.read_csv(path)

bee_man

import plotly.express as px

fig=px.line(bee_man,x='frame',y='x')
fig.show()

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=2, cols=1)

fig.add_trace(
    go.Line(x=bee_man['frame']/20, y=(bee_man['x']**2+bee_man['y']**2)**.5),
    row=1, col=1
)

fig.add_trace(
    go.Line(x=bee_man['frame']/20, y=bee_man['y']),
    row=2, col=1
)

fig.update_layout(height=800, width=600, title_text="bee0_head")
fig.show()

from ast import Name

from jupyter_dash import JupyterDash
from dash import dcc, html, Input, Output
from plotly.subplots import make_subplots
import plotly.graph_objects as go

app = JupyterDash(__name__)


app.layout = html.Div([
    html.H4(''),
    dcc.Graph(id="graph"),
    html.P("Bee:"),

     dcc.Dropdown(
         id="dropdown1",
         options=['head','thorax','abdomen'],
         value='head',
         clearable=False,
     ),
     dcc.Dropdown(
        id="dropdown2",
        options=['0', '1', '2','3','4'],
        value='0',
        clearable=False,
    )
])


@app.callback(
    Output("graph", "figure",),
    Input("dropdown1","value"),
    Input("dropdown2","value")
    )


def bee_select(option1,option2):
    path='/content/drive/MyDrive/Beetube/5min_clip/bee_'+option2+"_"+option1
    bee_tmp=pd.read_csv(path)

    bodypart={'head':'Head','thorax':"Thorax","abdomen":"Abdomen"}
    fig = make_subplots(rows=2, cols=1)

    fig.add_scatter(
      x=bee_tmp['frame']/20, y=bee_man['x'],
       row=1, col=1,name="x Position"
    )

    fig.add_scatter(
      x=bee_tmp['frame']/20, y=-(bee_man['y']-1150),
       row=2, col=1,name='y position'
    )

    fig.update_layout(
    height=300,
    title_text='Bee '+option2+"'s "+bodypart[option1]+ " Position",

    )
    fig.update_xaxes(title_text="Time (s)")
    fig.update_yaxes(title_text="Pixel")




    return fig

app.run_server(mode='inline',inline_exceptions=True)